[build]
  command = "cd client && npm run build:netlify"
  functions = "netlify/functions"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && npm run dev"
  port = 5173
  targetPort = 3000 